# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # Build the frontend first (similar to your build.sh)
    - sh -c "cd ./web/frontend/ && npm ci && npm run build"
    # Copy frontend dist to internal/web for embedding
    - rm -rf ./internal/web/dist
    - cp -r ./web/frontend/dist ./internal/web/

# Build configuration
builds:
  - id: scriberr
    main: ./cmd/server/main.go
    binary: vpscriber
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # Build flags
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}

# Archive configuration
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

# Checksum configuration
checksum:
  name_template: 'checksums.txt'

# Snapshot configuration
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

# GitHub Release configuration
release:
  github:
    owner: Szern
    name: VPScriber
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## VPScriber {{ .Tag }}
    
    This is only private test version!
    
    ### Installation
    
    #### Homebrew (macOS/Linux)
    ```bash
    brew tap szern/vpscriber
    brew install vpscriber
    ```

# Homebrew Tap configuration
homebrew_casks:
  - name: vpscriber
    repository:
      owner: szern
      name: homebrew-vpscriber
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    # Ensure the formula is placed under the conventional Formula/ directory
    directory: Casks
    homepage: https://github.com/szern/vpscriber
    description: "VPS version - Audio transcription service using WhisperX with speaker diarization"
    license: MIT
    dependencies:
      - formula: uv
    caveats: |
      Scriberr requires Python 3.11+ for transcription features.
      Install with: brew install python@3.11
      
      To get started:
      1. Run: scriberr
      2. Open: http://localhost:8080
      
      The app will auto-configure itself on first run.
